webtalk_init -webtalk_dir /home/indi/Documents/Computerarchitectuur_WPO/Project_MIPS/Project_MIPS.sim/sim_1/behav/xsim/xsim.dir/Branch_Top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 12 15:38:00 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "62faaf36-7a2d-40b6-b4b0-88848c276241" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "69d49c8143ca4da8b22e4a0c58e5c4d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 6900HS Creator Edition" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3293.719 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124908_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1808821427 -regid "" -xml /home/indi/Documents/Computerarchitectuur_WPO/Project_MIPS/Project_MIPS.sim/sim_1/behav/xsim/xsim.dir/Branch_Top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/indi/Documents/Computerarchitectuur_WPO/Project_MIPS/Project_MIPS.sim/sim_1/behav/xsim/xsim.dir/Branch_Top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/indi/Documents/Computerarchitectuur_WPO/Project_MIPS/Project_MIPS.sim/sim_1/behav/xsim/xsim.dir/Branch_Top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
