#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 13 11:13:47 CET 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 69d49c8143ca4da8b22e4a0c58e5c4d2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MIPSwUART_tb_behav xil_defaultlib.MIPSwUART_tb -log elaborate.log"
xelab -wto 69d49c8143ca4da8b22e4a0c58e5c4d2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MIPSwUART_tb_behav xil_defaultlib.MIPSwUART_tb -log elaborate.log

